# fly.toml app configuration file generated for board-worker on 2026-03-08T21:14:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'board-worker'
primary_region = 'bom'

[experimental]

[build]
  dockerfile = 'Dockerfile.worker'

[env]
  NODE_ENV = 'production'
  WORKER_ID = 'fly-prod-1'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
